# Generated by Django 4.2.7 on 2023-12-02 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeritaAlumni',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.CharField(max_length=100)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.alumni')),
            ],
        ),
    ]
