# Generated by Django 4.2.7 on 2023-12-04 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informasikarier', '0002_initial'),
        ('lowongankerja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lowongankerja',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lowongankerja',
            name='karier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informasikarier.karier'),
        ),
    ]
