# Generated by Django 4.2.7 on 2023-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowongankerja', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowongankerja',
            name='tanggal_tutup',
            field=models.DateTimeField(null=True),
        ),
    ]
