# Generated by Django 4.2.7 on 2023-12-04 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('npm', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('foto_profil', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('alumni', 'Alumni'), ('mahasiswa', 'Mahasiswa')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lomba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_lomba', models.CharField(max_length=100)),
                ('penyelenggara', models.CharField(max_length=100)),
                ('hasil_lomba', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lomba', models.ManyToManyField(related_name='lomba_mhs', to='user.lomba')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_perguruan_tinggi', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=100)),
                ('bidang', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendidikans_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pendidikan',
            field=models.ManyToManyField(related_name='pendidikan_users', to='user.pendidikan'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='PengalamanKerja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_pengalaman', models.CharField(max_length=100)),
                ('nama_instansi', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_akhir', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kerjas_alumni', to='user.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Pengalaman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_pengalaman', models.CharField(max_length=100)),
                ('nama_instansi', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_akhir', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengalaman_mahasiswa', to='user.mahasiswa')),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='pengalaman',
            field=models.ManyToManyField(related_name='pengalaman_mhs', to='user.pengalaman'),
        ),
        migrations.AddField(
            model_name='lomba',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lombas_mahasiswa', to='user.mahasiswa'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='pengalaman_kerja',
            field=models.ManyToManyField(related_name='alumni', to='user.pengalamankerja'),
        ),
    ]
