# Generated by Django 4.2.7 on 2023-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rekomendasi_karier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
