# Generated by Django 4.2.7 on 2023-11-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_alumni_managers_alter_mahasiswa_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alumni',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='mahasiswa',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
