# Generated by Django 4.2.7 on 2023-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_alumni_managers_alter_mahasiswa_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='pengalaman_kerja',
            field=models.ManyToManyField(related_name='alumni', to='user.pengalamankerja'),
        ),
    ]
