# Generated by Django 4.2.7 on 2023-11-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_alumni_pengalaman_kerja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
